language: go

go:
  - 1.3

install:
  - go get github.com/coreos/etcd
  - go get github.com/coreos/go-etcd/etcd
  - go get github.com/fsouza/go-dockerclient
  - go get github.com/dchest/uniuri

before_script:
  - go build -o $HOME/gopath/src/github.com/coreos/etcd/etcd.run github.com/coreos/etcd
  - $HOME/gopath/src/github.com/coreos/etcd/etcd.run &